-- =============================================================================
-- Migration 0015: Per-trucker visibility + reference codes + address rename.
--
-- Three threads in one migration because they all converge on the new shape
-- of create_load_with_items():
--   * Rename loads.origin_city / destination_city → origin_address /
--     destination_address (still text, but the UI is moving from city
--     dropdowns to free-form addresses).
--   * Add loads.reference_code: short 4-char human-quotable handle, auto-
--     generated by a BEFORE INSERT trigger, UNIQUE, NOT NULL. Char set
--     excludes visually confusing glyphs (0/O/1/I/L).
--   * Add load_trucker_visibility join table: per-load whitelist of which
--     truckers can see the load. Populated up-front when the load is
--     posted; an admin can edit it later (Part I).
--
-- create_load_with_items() is re-defined with a new 8-arg signature: the
-- two renamed address parameters plus a new p_trucker_ids uuid[]. The old
-- 7-arg version is dropped first because Postgres treats it as a distinct
-- overload (same name, different signature).
--
-- record_audit() and bid_audit_log.entity_type are extended to cover
-- load_trucker_visibility. Full restatement of record_audit() so the diff
-- review surfaces any branch regression (it has happened twice before).
--
-- Apply once in the Supabase SQL editor. The column renames assume an empty
-- loads table (true through every prior wipe migration); they will still
-- succeed on a populated table but downstream code that hardcodes the old
-- names would break at the same instant.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- 1. Rename loads.origin_city / destination_city → *_address
-- -----------------------------------------------------------------------------

alter table loads rename column origin_city      to origin_address;
alter table loads rename column destination_city to destination_address;


-- -----------------------------------------------------------------------------
-- 2. loads.reference_code (nullable for now; NOT NULL added in section 5)
-- -----------------------------------------------------------------------------
-- Partial unique index because reference_code is nullable in this section
-- and SQL's "NULL is not equal to NULL" would let a plain UNIQUE coexist
-- with many NULLs (which we do want pre-backfill) — but once NOT NULL is
-- set in section 5, the partial filter becomes effectively total. We keep
-- it as a partial index so the migration is order-independent for rollback.

alter table loads
  add column reference_code text;

create unique index loads_reference_code_idx
  on loads (reference_code)
  where reference_code is not null;


-- -----------------------------------------------------------------------------
-- 3. generate_load_reference_code() — random 4-char code generator
-- -----------------------------------------------------------------------------
-- 31 chars (23 letters + 8 digits) ^ 4 = 923,521 codes. With low six-figure
-- load counts the trigger's collision retry (section 4) handles birthday-
-- paradox edge cases. random() is fine for this — we are not protecting
-- against guessing attacks, just giving humans a short stable handle.
--
-- Char set deliberately excludes 0, O, 1, I, L so written/spoken codes
-- transcribe unambiguously.

create or replace function generate_load_reference_code()
returns text
language plpgsql
as $$
declare
  v_chars text := 'ABCDEFGHJKMNPQRSTUVWXYZ23456789';
  v_code  text;
  v_i     integer;
begin
  v_code := '';
  for v_i in 1..4 loop
    v_code := v_code || substr(
      v_chars,
      1 + floor(random() * length(v_chars))::integer,
      1
    );
  end loop;
  return v_code;
end;
$$;


-- -----------------------------------------------------------------------------
-- 4. set_load_reference_code() — BEFORE INSERT trigger
-- -----------------------------------------------------------------------------
-- Honors a caller-provided reference_code (useful for tests / data import).
-- Otherwise generates and retries on the very small chance of a same-string
-- collision against an existing row. The retry only catches "select-time"
-- collisions; a concurrent INSERT race could still trip the UNIQUE index,
-- but that surfaces as a clean failure and the application can retry the
-- whole RPC.

create or replace function set_load_reference_code()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_code         text;
  v_attempts     integer := 0;
  v_max_attempts integer := 20;
begin
  if NEW.reference_code is not null then
    return NEW;
  end if;

  loop
    v_code := generate_load_reference_code();
    if not exists (select 1 from loads where reference_code = v_code) then
      NEW.reference_code := v_code;
      return NEW;
    end if;
    v_attempts := v_attempts + 1;
    if v_attempts >= v_max_attempts then
      raise exception
        'Could not generate unique reference code after % attempts',
        v_max_attempts;
    end if;
  end loop;
end;
$$;

drop trigger if exists set_load_reference_code_trigger on loads;
create trigger set_load_reference_code_trigger
  before insert on loads
  for each row execute function set_load_reference_code();


-- -----------------------------------------------------------------------------
-- 5. reference_code NOT NULL
-- -----------------------------------------------------------------------------
-- Safe because loads is currently empty (the wipe in 0010 was never re-
-- populated by a test fixture). All future INSERTs route through the
-- trigger in section 4 which guarantees a non-null value.

alter table loads
  alter column reference_code set not null;


-- -----------------------------------------------------------------------------
-- 6. load_trucker_visibility join table
-- -----------------------------------------------------------------------------
-- Composite primary key prevents accidental duplicates. ON DELETE CASCADE
-- on both FKs is intentional: if a load row goes away (currently only via
-- SQL editor), its visibility rows go with it; same for truckers (though
-- we archive rather than delete, so this rarely fires in practice).

create table load_trucker_visibility (
  load_id     uuid not null references loads(id) on delete cascade,
  trucker_id  uuid not null references truckers(id) on delete cascade,
  created_at  timestamptz not null default now(),
  primary key (load_id, trucker_id)
);

-- The composite PK already indexes (load_id, trucker_id) → useful for
-- "is this trucker on the list for load X" lookups. The lookup that needs
-- its own index is the reverse: "which loads is this trucker allowed to
-- see" — fired on every /t/loads render.

create index load_trucker_visibility_trucker_idx
  on load_trucker_visibility (trucker_id);


-- -----------------------------------------------------------------------------
-- 7. RLS on load_trucker_visibility
-- -----------------------------------------------------------------------------
-- Reads open to authenticated (operators inspecting / truckers checking
-- visibility). Writes gated by is_operator() — admins are a subset of
-- operators, so is_operator() covers both.

alter table load_trucker_visibility enable row level security;

create policy load_trucker_visibility_select on load_trucker_visibility
  for select to authenticated using (true);

create policy load_trucker_visibility_insert on load_trucker_visibility
  for insert to authenticated with check (is_operator());

create policy load_trucker_visibility_update on load_trucker_visibility
  for update to authenticated
  using (is_operator()) with check (is_operator());

create policy load_trucker_visibility_delete on load_trucker_visibility
  for delete to authenticated using (is_operator());


-- -----------------------------------------------------------------------------
-- 8. create_load_with_items() — new 8-arg signature
-- -----------------------------------------------------------------------------
-- Renames p_origin_city / p_destination_city → p_*_address and adds
-- p_trucker_ids. The old 7-arg overload is dropped explicitly because
-- Postgres would otherwise keep it as a distinct function (same name,
-- different signature) and PostgREST would expose both.
--
-- zone_id is auto-populated by the BEFORE INSERT trigger from 0014.
-- reference_code is auto-populated by the BEFORE INSERT trigger from
-- section 4 above. Both fire on the same INSERT and are independent.

drop function if exists create_load_with_items(
  text, text, truck_type, timestamptz, bigint, text, jsonb
);

create or replace function create_load_with_items(
  p_origin_address         text,
  p_destination_address    text,
  p_truck_type_required    truck_type,
  p_pickup_deadline        timestamptz,
  p_reference_price_paise  bigint,
  p_notes                  text,
  p_items                  jsonb,
  p_trucker_ids            uuid[]
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_load_id    uuid;
  v_item       jsonb;
  v_pos        integer := 0;
  v_user_id    uuid;
  v_trucker_id uuid;
begin
  -- Auth guard: function bypasses RLS, so re-enforce operator-only here.
  v_user_id := auth.uid();
  if v_user_id is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  if not is_operator() then
    raise exception 'Only operators can create loads' using errcode = '42501';
  end if;

  if jsonb_array_length(p_items) < 1 then
    raise exception 'A load must have at least one product item';
  end if;

  if p_trucker_ids is null or array_length(p_trucker_ids, 1) is null then
    raise exception 'Select at least one trucker to make the load visible';
  end if;

  -- Insert the parent load. zone_id auto-filled by 0014 trigger;
  -- reference_code auto-filled by trigger from section 4.
  insert into loads (
    origin_address, destination_address, truck_type_required,
    pickup_deadline, reference_price_paise, notes, posted_by
  ) values (
    p_origin_address, p_destination_address, p_truck_type_required,
    p_pickup_deadline, p_reference_price_paise, p_notes, v_user_id
  )
  returning id into v_load_id;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    insert into load_items (
      load_id, position,
      product_name_id, container_type_id,
      quantity_value, quantity_unit_id,
      weight_value, weight_unit
    ) values (
      v_load_id, v_pos,
      (v_item->>'product_name_id')::uuid,
      (v_item->>'container_type_id')::uuid,
      (v_item->>'quantity_value')::numeric,
      (v_item->>'quantity_unit_id')::uuid,
      (v_item->>'weight_value')::numeric,
      v_item->>'weight_unit'
    );
    v_pos := v_pos + 1;
  end loop;

  foreach v_trucker_id in array p_trucker_ids
  loop
    insert into load_trucker_visibility (load_id, trucker_id)
    values (v_load_id, v_trucker_id);
  end loop;

  return v_load_id;
end;
$$;

revoke all on function create_load_with_items(
  text, text, truck_type, timestamptz, bigint, text, jsonb, uuid[]
) from public;

grant execute on function create_load_with_items(
  text, text, truck_type, timestamptz, bigint, text, jsonb, uuid[]
) to authenticated;


-- -----------------------------------------------------------------------------
-- 9. bid_audit_log.entity_type CHECK — allow 'load_visibility'
-- -----------------------------------------------------------------------------

alter table bid_audit_log
  drop constraint bid_audit_log_entity_type_check;

alter table bid_audit_log
  add constraint bid_audit_log_entity_type_check
  check (entity_type in (
    'bid', 'load', 'shipment', 'load_item', 'trucker', 'operator',
    'zone', 'load_visibility'
  ));


-- -----------------------------------------------------------------------------
-- 10. record_audit() — full body with all 8 branches
-- -----------------------------------------------------------------------------
-- Branches present, in order: bids, loads, shipments, load_items, truckers,
-- operators, zones, load_trucker_visibility.
--
-- Actor resolution unchanged: JWT auth.uid() first, then the trucker
-- session variable set by place_trucker_bid(), then 'system'.
--
-- Full restatement (not an incremental patch) because previous migrations
-- 0010 and 0011 each silently dropped a branch when they tried to patch
-- incrementally. Re-asserting the whole body makes regressions obvious in
-- diff review.

create or replace function record_audit()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_actor_id    uuid;
  v_actor_role  text;
  v_action      text;
  v_entity_type text;
  v_entity_id   uuid;
  v_load_id     uuid;
  v_before      jsonb;
  v_after       jsonb;
begin
  -- 10a. Actor identity: JWT first, then trucker session var, then system.
  v_actor_id := auth.uid();

  if v_actor_id is null then
    -- Fall back to the trucker session variable that place_trucker_bid()
    -- sets within its transaction. nullif(..., '') handles the case
    -- where the GUC was never SET.
    v_actor_id := nullif(current_setting('app.trucker_id', true), '')::uuid;
    if v_actor_id is not null then
      v_actor_role := 'trucker';
    else
      v_actor_role := 'system';
    end if;
  else
    select role::text into v_actor_role
      from operators where id = v_actor_id;
    if v_actor_role is null then
      v_actor_role := 'trucker';
    end if;
  end if;

  -- 10b. Serialize before/after rows as jsonb.
  if TG_OP = 'INSERT' then
    v_before := null;
    v_after  := to_jsonb(NEW);
  elsif TG_OP = 'UPDATE' then
    v_before := to_jsonb(OLD);
    v_after  := to_jsonb(NEW);
  elsif TG_OP = 'DELETE' then
    v_before := to_jsonb(OLD);
    v_after  := null;
  end if;

  -- 10c. Plural table name → singular entity_type.
  v_entity_type := case TG_TABLE_NAME
    when 'bids'                     then 'bid'
    when 'loads'                    then 'load'
    when 'shipments'                then 'shipment'
    when 'load_items'               then 'load_item'
    when 'truckers'                 then 'trucker'
    when 'operators'                then 'operator'
    when 'zones'                    then 'zone'
    when 'load_trucker_visibility'  then 'load_visibility'
  end;

  -- 10d. Per-table action label, entity_id, and load_id.
  if TG_TABLE_NAME = 'bids' then
    if TG_OP = 'INSERT' then
      v_action := 'bid_placed';
    elsif TG_OP = 'UPDATE' then
      if OLD.status is distinct from NEW.status then
        v_action := 'bid_' || NEW.status::text;
      else
        v_action := 'bid_updated';
      end if;
    elsif TG_OP = 'DELETE' then
      v_action := 'bid_deleted';
    end if;
    v_load_id   := coalesce(NEW.load_id, OLD.load_id);
    v_entity_id := coalesce(NEW.id, OLD.id);

  elsif TG_TABLE_NAME = 'loads' then
    if TG_OP = 'INSERT' then
      v_action := 'load_posted';
    elsif TG_OP = 'UPDATE' then
      if OLD.status is distinct from NEW.status then
        v_action := 'load_' || NEW.status::text;
      else
        v_action := 'load_updated';
      end if;
    elsif TG_OP = 'DELETE' then
      v_action := 'load_deleted';
    end if;
    v_load_id   := coalesce(NEW.id, OLD.id);
    v_entity_id := v_load_id;

  elsif TG_TABLE_NAME = 'shipments' then
    if TG_OP = 'INSERT' then
      v_action := 'shipment_created';
    elsif TG_OP = 'UPDATE' then
      v_action := 'shipment_updated';
    elsif TG_OP = 'DELETE' then
      v_action := 'shipment_deleted';
    end if;
    v_load_id   := coalesce(NEW.load_id, OLD.load_id);
    v_entity_id := coalesce(NEW.id, OLD.id);

  elsif TG_TABLE_NAME = 'load_items' then
    if TG_OP = 'INSERT' then
      v_action := 'load_item_added';
    elsif TG_OP = 'UPDATE' then
      v_action := 'load_item_updated';
    elsif TG_OP = 'DELETE' then
      v_action := 'load_item_removed';
    end if;
    v_load_id   := coalesce(NEW.load_id, OLD.load_id);
    v_entity_id := coalesce(NEW.id, OLD.id);

  elsif TG_TABLE_NAME = 'truckers' then
    if TG_OP = 'INSERT' then
      v_action := 'trucker_added';
    elsif TG_OP = 'UPDATE' then
      if OLD.archived_at is null and NEW.archived_at is not null then
        v_action := 'trucker_archived';
      elsif OLD.archived_at is not null and NEW.archived_at is null then
        v_action := 'trucker_unarchived';
      elsif OLD.status is distinct from NEW.status then
        v_action := 'trucker_status_' || NEW.status::text;
      else
        v_action := 'trucker_updated';
      end if;
    elsif TG_OP = 'DELETE' then
      v_action := 'trucker_deleted';
    end if;
    v_load_id   := null;
    v_entity_id := coalesce(NEW.id, OLD.id);

  elsif TG_TABLE_NAME = 'operators' then
    if TG_OP = 'INSERT' then
      v_action := 'operator_added';
    elsif TG_OP = 'UPDATE' then
      if OLD.archived_at is null and NEW.archived_at is not null then
        v_action := 'operator_archived';
      elsif OLD.archived_at is not null and NEW.archived_at is null then
        v_action := 'operator_unarchived';
      else
        v_action := 'operator_updated';
      end if;
    elsif TG_OP = 'DELETE' then
      v_action := 'operator_deleted';
    end if;
    v_load_id   := null;
    v_entity_id := coalesce(NEW.id, OLD.id);

  elsif TG_TABLE_NAME = 'zones' then
    if TG_OP = 'INSERT' then
      v_action := 'zone_added';
    elsif TG_OP = 'UPDATE' then
      if OLD.deleted_at is null and NEW.deleted_at is not null then
        v_action := 'zone_archived';
      elsif OLD.deleted_at is not null and NEW.deleted_at is null then
        v_action := 'zone_restored';
      else
        v_action := 'zone_updated';
      end if;
    elsif TG_OP = 'DELETE' then
      v_action := 'zone_deleted';
    end if;
    v_load_id   := null;
    v_entity_id := coalesce(NEW.id, OLD.id);

  elsif TG_TABLE_NAME = 'load_trucker_visibility' then
    if TG_OP = 'INSERT' then
      v_action := 'trucker_invited';
    elsif TG_OP = 'DELETE' then
      v_action := 'trucker_removed';
    else
      v_action := 'visibility_updated';
    end if;
    v_load_id   := coalesce(NEW.load_id, OLD.load_id);
    v_entity_id := coalesce(NEW.trucker_id, OLD.trucker_id);
  end if;

  insert into bid_audit_log (
    entity_type, entity_id, action, actor_id, actor_role,
    before, after, load_id
  ) values (
    v_entity_type, v_entity_id, v_action, v_actor_id, v_actor_role,
    v_before, v_after, v_load_id
  );

  if TG_OP = 'DELETE' then
    return OLD;
  else
    return NEW;
  end if;
end;
$$;


-- -----------------------------------------------------------------------------
-- 11. Audit trigger on load_trucker_visibility
-- -----------------------------------------------------------------------------

drop trigger if exists record_audit_load_trucker_visibility
  on load_trucker_visibility;
create trigger record_audit_load_trucker_visibility
  after insert or update or delete on load_trucker_visibility
  for each row execute function record_audit();
